MOUSEKEY_ENABLE    = yes    # Mouse keys
RGBLIGHT_ENABLE    = yes    # Enable WS2812 RGB underlight.
OLED_ENABLE        = yes
OLED_DRIVER        = SSD1306
LTO_ENABLE         = yes
RGB_MATRIX_ENABLE  = no
CONSOLE_ENABLE     = no
COMMAND_ENABLE     = no
EXTRAKEY_ENABLE    = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE   = no
MAGIC_ENABLE       = no
MUSIC_ENABLE       = no
