MOUSEKEY_ENABLE    = yes
COMBO_ENABLE       = yes
EXTRAKEY_ENABLE    = yes

RGB_MATRIX_ENABLE  = no
CONSOLE_ENABLE     = no
COMMAND_ENABLE     = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE   = no
MAGIC_ENABLE       = no
MUSIC_ENABLE       = no
BACKLIGHT_ENABLE   = no
TAP_DANCE_ENABLE   = no
